---
pid: /var/run/thin.pid
log: log/thin.log
port: 8000
timeout: 30
max_conns: 1024
chdir: /mnt/app/current
max_persistent_conns: 512
environment: production
address: 0.0.0.0
servers: 4
require: []

daemonize: true
user: app
group: app